<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;
use Illuminate\Validation\Rule;
use Throwable;

class AuthController extends Controller
{
    public function register(Request $request): JsonResponse
    {
        $payload = $request->validate([
            'first_name' => ['required', 'string', 'max:80'],
            'last_name' => ['required', 'string', 'max:80'],
            'email' => ['required', 'email', 'max:120', Rule::unique('users', 'email')],
            'cin' => ['required', 'string', 'max:40', Rule::unique('users', 'cin')],
            'class_name' => ['required', 'string', 'max:120'],
            'filiere' => ['required', 'string', 'max:120'],
            'password' => ['required', 'string', 'min:8', 'confirmed'],
        ], [
            'email.unique' => 'Le gmail que vous avez saisi existe deja.',
            'cin.unique' => 'Le CIN que vous avez saisi existe deja.',
        ]);

        $firstName = trim((string) $payload['first_name']);
        $lastName = trim((string) $payload['last_name']);

        /** @var User $user */
        $user = User::query()->create([
            'name' => trim($firstName.' '.$lastName),
            'first_name' => $firstName,
            'last_name' => $lastName,
            'email' => strtolower(trim((string) $payload['email'])),
            'cin' => trim((string) $payload['cin']),
            'class_name' => trim((string) $payload['class_name']),
            'filiere' => trim((string) $payload['filiere']),
            'password' => (string) $payload['password'],
            'role' => 'stagiaire',
        ]);

        // Student ID is generated by the system and is not user-editable.
        $user->student_id = 'STG'.str_pad((string) $user->id, 6, '0', STR_PAD_LEFT);
        $user->save();

        return response()->json([
            'message' => 'Account created successfully. You can now sign in.',
            'user' => $user,
        ], 201);
    }

    public function forgotPassword(Request $request): JsonResponse
    {
        $payload = $request->validate([
            'email' => ['required', 'email'],
        ]);

        $email = strtolower(trim((string) $payload['email']));
        $userExists = User::query()->where('email', $email)->exists();

        if (! $userExists) {
            return response()->json([
                'message' => 'Aucun compte trouve avec cet email. Retour a la page de connexion.',
            ], 404);
        }

        $latestRow = DB::table('password_reset_codes')
            ->where('email', $email)
            ->orderByDesc('id')
            ->first();

        if (
            $latestRow
            && ! Carbon::parse($latestRow->expires_at)->isPast()
            && Carbon::parse($latestRow->created_at)->gt(Carbon::now()->subSeconds(45))
        ) {
            return response()->json([
                'message' => 'Veuillez patienter quelques secondes avant de demander un nouveau code.',
            ], 429);
        }

        $code = str_pad((string) random_int(0, 999999), 6, '0', STR_PAD_LEFT);

        DB::table('password_reset_codes')->where('email', $email)->delete();
        DB::table('password_reset_codes')->insert([
            'email' => $email,
            'code_hash' => hash('sha256', $code),
            'expires_at' => Carbon::now()->addMinutes(15),
            'created_at' => now(),
            'updated_at' => now(),
        ]);

        $logoUrl = rtrim((string) config('app.url'), '/').'/image.png';

        try {
            Mail::send(
                'emails.password-reset-code',
                [
                    'code' => $code,
                    'logoUrl' => $logoUrl,
                ],
                function ($message) use ($email): void {
                    $message->to($email)->subject('CMC SportBooking - Code verification');
                }
            );
        } catch (Throwable $e) {
            $rawMessage = $e->getMessage();

            Log::error('Failed to send password reset code email.', [
                'email' => $email,
                'exception' => $rawMessage,
            ]);

            $message = 'Service email indisponible pour le moment. Veuillez reessayer dans quelques minutes.';

            return response()->json([
                'message' => $message,
            ], 503);
        }

        return response()->json(['message' => 'Verification code sent to your email.']);
    }

    public function verifyResetCode(Request $request): JsonResponse
    {
        $payload = $request->validate([
            'email' => ['required', 'email'],
            'code' => ['required', 'digits:6'],
        ]);

        $email = strtolower(trim((string) $payload['email']));
        $code = trim((string) $payload['code']);

        $row = DB::table('password_reset_codes')
            ->where('email', $email)
            ->orderByDesc('id')
            ->first();

        if (! $row || Carbon::parse($row->expires_at)->isPast()) {
            return response()->json(['message' => 'Code expired or invalid.'], 422);
        }

        if ((int) $row->attempts >= 5) {
            DB::table('password_reset_codes')->where('id', $row->id)->delete();

            return response()->json([
                'message' => 'Trop de tentatives. Veuillez demander un nouveau code.',
            ], 429);
        }

        if (! hash_equals((string) $row->code_hash, hash('sha256', $code))) {
            $nextAttempts = (int) $row->attempts + 1;

            DB::table('password_reset_codes')
                ->where('id', $row->id)
                ->update([
                    'attempts' => $nextAttempts,
                    'updated_at' => now(),
                ]);

            if ($nextAttempts >= 5) {
                DB::table('password_reset_codes')->where('id', $row->id)->delete();

                return response()->json([
                    'message' => 'Trop de tentatives. Veuillez demander un nouveau code.',
                ], 429);
            }

            return response()->json(['message' => 'Verification code is incorrect.'], 422);
        }

        $resetToken = bin2hex(random_bytes(32));

        DB::table('password_reset_codes')
            ->where('id', $row->id)
            ->update([
                'verified_at' => now(),
                'reset_token_hash' => hash('sha256', $resetToken),
                'updated_at' => now(),
            ]);

        return response()->json([
            'message' => 'Code verified successfully.',
            'reset_token' => $resetToken,
        ]);
    }

    public function resetPassword(Request $request): JsonResponse
    {
        $payload = $request->validate([
            'email' => ['required', 'email'],
            'reset_token' => ['required', 'string', 'min:20'],
            'new_password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);

        $email = strtolower(trim((string) $payload['email']));
        $resetToken = trim((string) $payload['reset_token']);

        $row = DB::table('password_reset_codes')
            ->where('email', $email)
            ->orderByDesc('id')
            ->first();

        if (! $row || ! $row->verified_at || Carbon::parse($row->expires_at)->isPast()) {
            return response()->json(['message' => 'Reset session expired. Please request a new code.'], 422);
        }

        if (! $row->reset_token_hash || ! hash_equals((string) $row->reset_token_hash, hash('sha256', $resetToken))) {
            return response()->json(['message' => 'Invalid reset session.'], 422);
        }

        $user = User::query()->where('email', $email)->first();
        if (! $user) {
            return response()->json(['message' => 'User not found.'], 404);
        }

        $user->password = (string) $payload['new_password'];
        $user->save();

        DB::table('password_reset_codes')->where('email', $email)->delete();

        return response()->json(['message' => 'Password reset successful.']);
    }

    public function login(Request $request): JsonResponse
    {
        $payload = $request->validate([
            'email' => ['required', 'email'],
            'password' => ['required', 'string', 'min:6'],
            'portal' => ['required', 'in:admin,stagiaire'],
        ]);

        /** @var User|null $user */
        $user = User::where('email', $payload['email'])->first();

        if (!$user || !Hash::check($payload['password'], $user->password)) {
            return response()->json(['message' => 'Invalid credentials'], 422);
        }

        if ($payload['portal'] === 'admin') {
            $adminEmail = env('ADMIN_EMAIL', 'admin@cmc-sportbooking.ma');
            if ($user->role !== 'admin' || $user->email !== $adminEmail) {
                return response()->json(['message' => 'Admin access denied'], 403);
            }
        }

        if ($payload['portal'] === 'stagiaire' && $user->role !== 'stagiaire') {
            return response()->json(['message' => 'Stagiaire access denied'], 403);
        }

        $plainToken = bin2hex(random_bytes(40));
        $user->api_token = hash('sha256', $plainToken);
        $user->save();

        return response()->json([
            'token' => $plainToken,
            'user' => $user,
        ]);
    }

    public function me(Request $request): JsonResponse
    {
        return response()->json([
            'user' => $request->user(),
        ]);
    }

    public function updateMe(Request $request): JsonResponse
    {
        /** @var User|null $user */
        $user = $request->user();

        if (!$user) {
            return response()->json(['message' => 'Unauthorized'], 401);
        }

        $data = $request->validate([
            'first_name' => ['sometimes', 'nullable', 'string', 'max:80'],
            'last_name' => ['sometimes', 'nullable', 'string', 'max:80'],
            'name' => ['sometimes', 'nullable', 'string', 'max:120'],
            'email' => ['sometimes', 'email', 'max:120', 'unique:users,email,'.$user->id],
            'cin' => ['sometimes', 'nullable', 'string', 'max:40'],
            'class_name' => ['sometimes', 'nullable', 'string', 'max:120'],
            'filiere' => ['sometimes', 'nullable', 'string', 'max:120'],
        ]);

        if (
            array_key_exists('first_name', $data)
            || array_key_exists('last_name', $data)
            || array_key_exists('name', $data)
        ) {
            $first = trim((string) ($data['first_name'] ?? $user->first_name ?? ''));
            $last = trim((string) ($data['last_name'] ?? $user->last_name ?? ''));
            $fallbackName = trim((string) ($data['name'] ?? $user->name ?? ''));
            $fullName = trim($first.' '.$last);

            $data['first_name'] = $first !== '' ? $first : null;
            $data['last_name'] = $last !== '' ? $last : null;
            $data['name'] = $fullName !== '' ? $fullName : $fallbackName;
        }

        if (array_key_exists('cin', $data)) {
            $data['cin'] = filled($data['cin'] ?? null) ? trim((string) $data['cin']) : null;
        }

        if (array_key_exists('class_name', $data)) {
            $data['class_name'] = filled($data['class_name'] ?? null) ? trim((string) $data['class_name']) : null;
        }

        if (array_key_exists('filiere', $data)) {
            $data['filiere'] = filled($data['filiere'] ?? null) ? trim((string) $data['filiere']) : null;
        }

        if (array_key_exists('email', $data)) {
            $data['email'] = strtolower(trim((string) $data['email']));
        }

        $user->update($data);

        return response()->json([
            'message' => 'Profile updated successfully',
            'user' => $user->fresh(),
        ]);
    }

    public function logout(Request $request): JsonResponse
    {
        $user = $request->user();

        if ($user) {
            $user->api_token = null;
            $user->save();
        }

        return response()->json(['message' => 'Logged out']);
    }

    public function updatePassword(Request $request): JsonResponse
    {
        $payload = $request->validate([
            'current_password' => ['required', 'string', 'min:6'],
            'new_password' => ['required', 'string', 'min:8', 'confirmed'],
        ]);

        /** @var User|null $user */
        $user = $request->user();

        if (!$user || !Hash::check($payload['current_password'], $user->password)) {
            return response()->json(['message' => 'Current password is incorrect'], 422);
        }

        $user->password = $payload['new_password'];
        $user->save();

        return response()->json(['message' => 'Password updated successfully']);
    }
}
